/** Generado por scripts/generate-catalog.mjs */
import type { ImageSourcePropType } from 'react-native';

const images: Record<number, ImageSourcePropType> = {
  1: require("../../../assets/catalog/p1.jpg"),
  2: require("../../../assets/catalog/p2.jpg"),
  3: require("../../../assets/catalog/p3.jpg"),
  4: require("../../../assets/catalog/p4.jpg"),
  19: require("../../../assets/catalog/p19.jpg"),
  20: require("../../../assets/catalog/p20.jpg"),
  21: require("../../../assets/catalog/p21.jpg"),
  22: require("../../../assets/catalog/p22.jpg"),
  23: require("../../../assets/catalog/p23.jpg"),
  24: require("../../../assets/catalog/p24.jpg"),
  25: require("../../../assets/catalog/p25.jpg"),
  26: require("../../../assets/catalog/p26.jpg"),
  27: require("../../../assets/catalog/p27.jpg"),
  28: require("../../../assets/catalog/p28.jpg"),
  29: require("../../../assets/catalog/p29.jpg"),
  30: require("../../../assets/catalog/p30.jpg"),
  31: require("../../../assets/catalog/p31.jpg"),
  32: require("../../../assets/catalog/p32.jpg"),
  33: require("../../../assets/catalog/p33.jpg"),
  34: require("../../../assets/catalog/p34.jpg"),
  35: require("../../../assets/catalog/p35.jpg"),
  36: require("../../../assets/catalog/p36.png"),
  37: require("../../../assets/catalog/p37.webp"),
  38: require("../../../assets/catalog/p38.jpg"),
  39: require("../../../assets/catalog/p39.jpg"),
  40: require("../../../assets/catalog/p40.jpg"),
  41: require("../../../assets/catalog/p41.webp"),
  42: require("../../../assets/catalog/p42.webp"),
  43: require("../../../assets/catalog/p43.webp"),
  44: require("../../../assets/catalog/p44.webp"),
  45: require("../../../assets/catalog/p45.jpg"),
  46: require("../../../assets/catalog/p46.jpg"),
  47: require("../../../assets/catalog/p47.webp"),
  48: require("../../../assets/catalog/p48.jpg"),
  49: require("../../../assets/catalog/p49.jpg"),
  50: require("../../../assets/catalog/p50.jpg"),
  51: require("../../../assets/catalog/p51.webp"),
  52: require("../../../assets/catalog/p52.jpg"),
  53: require("../../../assets/catalog/p53.jpg"),
  54: require("../../../assets/catalog/p54.jpg"),
  55: require("../../../assets/catalog/p55.jpg"),
  56: require("../../../assets/catalog/p56.jpg"),
  57: require("../../../assets/catalog/p57.jpg"),
  58: require("../../../assets/catalog/p58.jpg"),
  59: require("../../../assets/catalog/p59.jpg"),
  60: require("../../../assets/catalog/p60.jpg"),
  61: require("../../../assets/catalog/p61.webp"),
  62: require("../../../assets/catalog/p62.jpg"),
  63: require("../../../assets/catalog/p63.jpg"),
  64: require("../../../assets/catalog/p64.jpg"),
  65: require("../../../assets/catalog/p65.jpg"),
  66: require("../../../assets/catalog/p66.jpg"),
  67: require("../../../assets/catalog/p67.jpg"),
  68: require("../../../assets/catalog/p68.jpg"),
  69: require("../../../assets/catalog/p69.jpg"),
  70: require("../../../assets/catalog/p70.jpg"),
  71: require("../../../assets/catalog/p71.jpg"),
  72: require("../../../assets/catalog/p72.jpg"),
  73: require("../../../assets/catalog/p73.jpg"),
  74: require("../../../assets/catalog/p74.jpg"),
  75: require("../../../assets/catalog/p75.jpg"),
  76: require("../../../assets/catalog/p76.jpg"),
  77: require("../../../assets/catalog/p77.jpg"),
  78: require("../../../assets/catalog/p78.jpg"),
  79: require("../../../assets/catalog/p79.jpg"),
  80: require("../../../assets/catalog/p80.jpg"),
  81: require("../../../assets/catalog/p81.jpg"),
  82: require("../../../assets/catalog/p82.webp"),
  83: require("../../../assets/catalog/p83.webp"),
  84: require("../../../assets/catalog/p84.jpg"),
};

export default images;
