import { StyleSheet } from 'react-native';

export function createAppStyles(scale: number, _isSmallScreen: boolean, isTablet: boolean, screenWidth: number) {
  return StyleSheet.create({
  actionsRow: {flexDirection: 'row',
    gap: 8,
    marginTop: 10,
  },
  addBtn: {backgroundColor: '#d2b06b', borderRadius: 10, paddingVertical: 10, paddingHorizontal: 16 },
  addButton: {backgroundColor: '#b4812f',
  },
  adminLink: {color: '#d2b06b', marginTop: 8, fontSize: 22, fontWeight: '700' },
  adminModalClose: {color: '#d2b06b', fontSize: Math.round(15 * scale), fontWeight: '700'},
  adminModalHeader: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: Math.round(16 * scale), paddingVertical: Math.round(12 * scale), borderBottomWidth: 1, borderBottomColor: '#2a2217'},
  adminModalSheet: {flex: 1, backgroundColor: '#0a0908', marginTop: Math.round(48 * scale)},
  adminModalTitle: {color: '#f4ead8', fontSize: Math.round(17 * scale), fontWeight: '800'},
  brandName: {color: '#f5ebdd',
    fontSize: 18,
    fontWeight: '700',
  },
  btnText: {color: '#fff', fontWeight: '700' },
  buttonText: {color: '#fff',
    fontWeight: '700',
  },
  cartBadge: {position: 'absolute',
    top: -5,
    right: -5,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#2bd56f',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  cartBadgeText: {fontSize: 10, fontWeight: '800', color: '#052010' },
  cartBar: {position: 'absolute',
    left: 8,
    right: 8,
    bottom: 8,
    backgroundColor: '#141414',
    borderWidth: 1,
    borderColor: '#2f2a22',
    borderRadius: 14,
    padding: 10,
  },
  cartBarButton: {backgroundColor: '#1d8f43', borderRadius: 10, alignItems: 'center', paddingVertical: 10 },
  cartBarButtonText: {color: '#f3fff7', fontWeight: '700' },
  cartBarText: {color: '#f0e1c8', fontSize: 15, marginBottom: 8 },
  cartBox: {backgroundColor: '#fff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderWidth: 1,
    borderColor: '#eadfce',
    padding: 12,
    marginHorizontal: 8,
    marginBottom: 8,
    marginTop: 4,
  },
  cartIcon: {width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#534126',
    backgroundColor: '#1b1813',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartIconText: {color: '#f4d8a3', fontSize: 18 },
  cartModalBack: {color: '#d2b06b', fontSize: Math.round(14 * scale), fontWeight: '700'},
  cartModalBackBtn: {paddingVertical: Math.round(6 * scale)},
  cartModalBody: {paddingHorizontal: Math.round(16 * scale), paddingVertical: Math.round(12 * scale)},
  cartModalEmpty: {color: '#8a7d6a', textAlign: 'center', paddingVertical: Math.round(32 * scale), fontSize: Math.round(15 * scale)},
  cartModalFooter: {padding: Math.round(16 * scale), borderTopWidth: 1, borderTopColor: '#2a2217'},
  cartModalHeader: {flexDirection: 'row', alignItems: 'center', paddingHorizontal: Math.round(16 * scale), paddingVertical: Math.round(14 * scale), borderBottomWidth: 1, borderBottomColor: '#2a2217'},
  cartModalLine: {flexDirection: 'row', alignItems: 'center', gap: Math.round(10 * scale), marginBottom: Math.round(12 * scale)},
  cartModalLineInfo: {flex: 1},
  cartModalLineName: {color: '#f4ead8', fontSize: Math.round(14 * scale), fontWeight: '700'},
  cartModalLinePrice: {color: '#d9b778', fontSize: Math.round(13 * scale), marginTop: Math.round(4 * scale)},
  cartModalQtyBtn: {width: Math.round(32 * scale), height: Math.round(32 * scale), borderRadius: Math.round(8 * scale), backgroundColor: '#2a2418', alignItems: 'center', justifyContent: 'center'},
  cartModalQtyRow: {flexDirection: 'row', alignItems: 'center', gap: Math.round(8 * scale)},
  cartModalQtyText: {color: '#f4ead8', fontSize: Math.round(15 * scale), fontWeight: '800', minWidth: Math.round(24 * scale), textAlign: 'center'},
  cartModalSendBtn: {backgroundColor: '#1d8f43', borderRadius: Math.round(12 * scale), paddingVertical: Math.round(14 * scale), alignItems: 'center'},
  cartModalSendText: {color: '#fff', fontWeight: '800', fontSize: Math.round(15 * scale)},
  cartModalTitle: {flex: 1, textAlign: 'center', color: '#f4ead8', fontSize: Math.round(18 * scale), fontWeight: '800'},
  cartModalTotal: {color: '#f4ead8', fontSize: Math.round(17 * scale), fontWeight: '800', marginBottom: Math.round(12 * scale)},
  cartTitle: {color: '#3d2d1d',
    fontWeight: '700',
  },
  cartTopRow: {flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cartTotal: {color: '#1d8f43',
    fontWeight: '700',
  },
  categoriesContainer: {gap: 8,
    paddingVertical: 8,
    paddingRight: 16,
  },
  categoriesWrap: {flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 14,
  },
  categoryCard: {backgroundColor: '#151515',
    borderWidth: 1,
    borderColor: '#2f2a22',
    borderRadius: 14,
    paddingVertical: 22,
    paddingHorizontal: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryCardActive: {borderColor: '#d2b06b', backgroundColor: '#242016' },
  categoryCardIcon: {fontSize: 36, marginBottom: 8 },
  categoryCardText: {color: '#f0e3cc', fontSize: 30, fontWeight: '700' },
  categoryChip: {backgroundColor: '#fff',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#dfd2bf',
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  categoryChipActive: {backgroundColor: '#f1d39d',
    borderColor: '#b07a24',
  },
  categoryEmoji: {fontSize: 14,
  },
  categoryEmojiActive: {transform: [{ scale: 1.05 }],
  },
  categoryGrid: {gap: 12 },
  categoryText: {color: '#4f3f2e',
    fontWeight: '600',
    fontSize: 13,
  },
  categoryTextActive: {color: '#3d2a12',
  },
  contactButton: {backgroundColor: '#2ddb74',
    borderRadius: 14,
    alignItems: 'center',
    paddingVertical: 14,
    marginTop: 18,
  },
  contactButtonText: {color: '#eaffef', fontWeight: '800', fontSize: 24 },
  contactLead: {color: '#ded2bf', fontSize: 34, fontWeight: '700', textAlign: 'center' },
  contactText: {color: '#baa98f', fontSize: 24, textAlign: 'center', marginTop: 10, lineHeight: 32 },
  container: {flex: 1,
    backgroundColor: '#0f0e0c',
  },
  detailModalAddBtn: {backgroundColor: '#d2b06b', borderRadius: Math.round(12 * scale), paddingVertical: Math.round(14 * scale), alignItems: 'center', marginTop: Math.round(16 * scale)},
  detailModalBody: {padding: Math.round(16 * scale)},
  detailModalCloseBtn: {position: 'absolute', top: Math.round(12 * scale), right: Math.round(12 * scale), backgroundColor: 'rgba(0,0,0,0.55)', borderRadius: Math.round(20 * scale), width: Math.round(36 * scale), height: Math.round(36 * scale), alignItems: 'center', justifyContent: 'center'},
  detailModalCloseText: {color: '#fff', fontSize: Math.round(18 * scale), fontWeight: '700'},
  detailModalDesc: {color: '#9c8f7b', fontSize: Math.round(14 * scale), lineHeight: Math.round(20 * scale), marginTop: Math.round(12 * scale)},
  detailModalImage: {width: '100%', height: Math.round(280 * scale), backgroundColor: '#1a1814'},
  detailModalPrice: {color: '#d9b778', fontSize: Math.round(18 * scale), fontWeight: '800', marginTop: Math.round(8 * scale)},
  detailModalSheet: {backgroundColor: '#12100c', marginHorizontal: Math.round(12 * scale), borderRadius: Math.round(18 * scale), overflow: 'hidden', maxHeight: '88%'},
  detailModalTitle: {color: '#f4ead8', fontSize: Math.round(20 * scale), fontWeight: '800'},
  emptyText: {textAlign: 'center',
    color: '#7a6651',
    paddingVertical: 24,
    fontSize: 14,
  },
  filterChip: {borderWidth: 1,
    borderColor: '#3b3227',
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 12,
  },
  filterChipActive: {backgroundColor: '#d2b06b', borderColor: '#d2b06b' },
  filterChipText: {color: '#bfae91', fontWeight: '600', fontSize: 15 },
  filterChipTextActive: {color: '#20190f' },
  filterWrap: {flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  footerBox: {marginTop: 24,
    borderTopWidth: 1,
    borderTopColor: '#2a2217',
    paddingTop: 16,
    alignItems: 'center',
    paddingBottom: 16,
  },
  footerBrand: {color: '#f0e2cc', fontSize: 38, fontWeight: '600' },
  footerText: {color: '#9c8f7b', marginTop: 6, textAlign: 'center', fontSize: 20 },
  headerContainer: {paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  headerTop: {backgroundColor: '#18130f',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#3a2d1f',
    padding: 14,
    marginBottom: 10,
  },
  heroButton: {alignSelf: 'flex-start',
    marginTop: 22,
    backgroundColor: '#d2b06b',
    paddingVertical: 14,
    paddingHorizontal: 26,
    borderRadius: 14,
  },
  heroButtonText: {color: '#1f1a12', fontWeight: '800', fontSize: 18 },
  heroSection: {paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 32,
    backgroundColor: '#090909',
    borderBottomWidth: 1,
    borderBottomColor: '#2a2217',
  },
  heroSubtitle: {color: '#b8ab97', marginTop: 14, fontSize: 26, lineHeight: 36 },
  heroTitle: {color: '#f6efe3', fontSize: 52, lineHeight: 58, fontWeight: '600' },
  logoText: {color: '#f4e9d9', fontSize: Math.round(22 * scale), fontWeight: '600' },
  menuAdminText: { color: '#d2b06b' },
  menuButton: { width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#534126',
    backgroundColor: '#1b1813',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuButtonText: {color: '#f4e9d9', fontSize: Math.round(22 * scale), marginTop: -2 },
  menuItem: {paddingVertical: 10, paddingHorizontal: 12 },
  menuItemText: {color: '#ddd1bb', fontWeight: '600', fontSize: 16 },
  menuOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.45)', alignItems: 'flex-end', paddingTop: 66, paddingRight: 14 },
  menuPanel: {width: 210,
    backgroundColor: '#171514',
    borderWidth: 1,
    borderColor: '#3d3427',
    borderRadius: 12,
    paddingVertical: 4,
  },
  menuTrigger: {width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#251c12',
    borderWidth: 1,
    borderColor: '#7a5a2b',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuTriggerText: {color: '#f4d9a8',
    fontSize: 18,
    marginTop: -1,
  },
  modalOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.72)', justifyContent: 'flex-end'},
  modalSheet: {backgroundColor: '#12100c', borderTopLeftRadius: Math.round(20 * scale), borderTopRightRadius: Math.round(20 * scale), maxHeight: '92%'},
  navMenuCloseArea: {flex: 1},
  navMenuItem: {paddingVertical: Math.round(16 * scale), paddingHorizontal: Math.round(20 * scale), borderBottomWidth: 1, borderBottomColor: '#2a2217'},
  navMenuItemText: {color: '#f4ead8', fontSize: Math.round(16 * scale), fontWeight: '700'},
  navMenuOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.5)'},
  navMenuTitle: {color: '#d2b06b', fontSize: Math.round(13 * scale), fontWeight: '800', paddingHorizontal: Math.round(20 * scale), paddingBottom: Math.round(8 * scale), textTransform: 'uppercase'},
  productActions: {flexDirection: 'row', gap: 10, paddingHorizontal: 12, marginTop: 10 },
  productCard: {backgroundColor: '#151515',
    borderWidth: 1,
    borderColor: '#2f2a22',
    borderRadius: 14,
    marginBottom: 12,
    overflow: 'hidden',
    paddingBottom: 12,
  },
  productCardBody: {padding: Math.round(10 * scale)},
  productContent: {flex: 1,
  },
  productDesc: {color: '#baab94', fontSize: 21, paddingHorizontal: 12, marginTop: 4, lineHeight: 28 },
  productDescription: {color: '#6d5a47',
    marginTop: 4,
    fontSize: 13,
  },
  productEmoji: {fontSize: 24,
  },
  productEmojiBox: {width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#fef4e5',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#efd7b2',
  },
  productImageEmoji: {fontSize: 52 },
  productImageMock: {height: 140,
    backgroundColor: '#231f17',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#2f2a22',
  },
  productName: {color: '#f4ead8', fontSize: 32, fontWeight: '600', paddingHorizontal: 12, marginTop: 10 },
  productPrice: {color: '#d9b778', fontSize: 29, fontWeight: '700', paddingHorizontal: 12, marginTop: 8 },
  productsContainer: {paddingBottom: 14,
    gap: 10,
  },
  removeBtn: {backgroundColor: '#85535f', borderRadius: 10, paddingVertical: 10, paddingHorizontal: 16 },
  removeButton: {backgroundColor: '#946066',
  },
  safeArea: {flex: 1, backgroundColor: '#060606' },
  scroll: {flex: 1 },
  scrollContent: {paddingBottom: Math.round(132 * scale) },
  section: {paddingHorizontal: 20, paddingTop: 24 },
  sectionTitle: {color: '#f4ead8', fontSize: 44, fontWeight: '600', marginBottom: 16 },
  stepCard: {backgroundColor: '#151515',
    borderWidth: 1,
    borderColor: '#2f2a22',
    borderRadius: 14,
    paddingVertical: 18,
    paddingHorizontal: 14,
    marginBottom: 12,
    alignItems: 'center',
  },
  stepNumber: {width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: '#d2b06b',
    color: '#1d170f',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 30,
    fontWeight: '800',
    marginBottom: 10,
  },
  stepText: {color: '#baa98f', textAlign: 'center', fontSize: 23, lineHeight: 30 },
  stepTitle: {color: '#f4ead8', fontSize: 32, fontWeight: '600', marginBottom: 6 },
  subtitle: {color: '#d9c6a2',
    marginTop: 4,
    fontSize: 14,
  },
  summaryChip: {flex: 1,
    backgroundColor: '#18130f',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3a2d1f',
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  summaryChipLabel: {color: '#bfa98a',
    fontSize: 12,
  },
  summaryChipValue: {color: '#f4e4ca',
    fontWeight: '700',
    marginTop: 2,
  },
  summaryRow: {flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  title: {color: '#f7ead6',
    fontSize: 29,
    fontWeight: '800',
  },
  topBar: {paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 6,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topNav: {height: 68,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2a2217',
    backgroundColor: '#0f0f0f',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topNavActions: {flexDirection: 'row', alignItems: 'center', gap: 10 },
  whatsFab: {position: 'absolute',
    right: 18,
    bottom: 88,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#2ddb74',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2ddb74',
    shadowOpacity: 0.45,
    shadowRadius: 14,
    elevation: 10,
  },
  whatsFabText: {fontSize: 26 },
  whatsappButton: {backgroundColor: '#1a7f3a',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  whatsappButtonText: {color: '#fff',
    fontWeight: '700',
  },
  whatsappFab: {position: 'absolute',
    right: 18,
    bottom: 88,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#2ddb74',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#2ddb74',
    shadowOpacity: 0.45,
    shadowRadius: 14,
    elevation: 10,
  },
  productGrid: { gap: 12 },
  productImage: { width: '100%', height: '100%' },
  loadMoreBtn: {
    marginTop: 12,
    borderWidth: 1,
    borderColor: '#3b3227',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: '#1a1a1a',
  },
  loadMoreText: { color: '#d2b06b', fontWeight: '700', fontSize: 15 },
  stepsGrid: { gap: 12 },
  });
}
